### ISSUE TITLE
[REVIEW]: Missing DOIs

### ISSUE THREAD

**Issue by pitmonticone** [casasglobal-org/psymple#57]
Dear authors,

Please review the [missing DOIs](https://github.com/openjournals/joss-reviews/issues/7364#issuecomment-2420703213) and ensure the references are updated accordingly.

Once you have completed this, please confirm by posting the following comment in the review thread [here](https://github.com/openjournals/joss-reviews/issues/7364):

```
@editorialbot check references
```

REVIEW ISSUE: https://github.com/openjournals/joss-reviews/issues/7364

**Comment by GJHSimmons** [comment]
@pitmonticone Firstly, thank you for agreeing to review this package. I will be working through the issues properly next week.

The three 'skipped' have no corresponding DOIs (2x are old papers with no online version, 1x is a Github repo which has not had a DOI created). Please advise how to continue.

**Comment by pitmonticone** [comment]
Hi @GJHSimmons, thank you for your response. 

As there are no corresponding DOIs, I believe this resolves the issue.
